#!/bin/bash
sudo yum update -y
sudo yum install httpd php wget -y
sudo wget -O /var/www/html/dc.gif https://raw.githubusercontent.com/bhiravabhatla/aws-compute-tutorials/master/ALB/dc.gif
sudo wget -O /var/www/html/index.php https://raw.githubusercontent.com/bhiravabhatla/aws-compute-tutorials/master/ALB/index-dc.php
echo "Alias /DC /var/www/html" >> /etc/httpd/conf/httpd.conf
sudo systemctl start httpd
sudo systemctl enable httpd
