---
- name: Install wordpress
  hosts: dev
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Start and Enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Enable PHP 7.3
      shell: amazon-linux-extras disable php7.2 && amazon-linux-extras enable php7.3

    - name: Install PHP components
      shell: amazon-linux-extras install php7.3 -y

    - name: Install python mysql for ansible
      yum: name=MySQL-python state=present

    - name: Install mysql repo
      yum:
        name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
        state: installed

    - name: Install mysql
      yum:
        name: [ 'mysql-community-server', 'mysql-community-common', 'mysql-community-libs' , 'mysql-community-client' ]
        state: installed

    - name: Start mysqld
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Retrieve the temp mysql root password
      shell: 'grep ''temporary password'' /var/log/mysqld.log | awk ''{print $11}'''
      register: mysql_temp_password
      ignore_errors: yes

    - name: Update mysql root password with temp password
      shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}''); FLUSH PRIVILEGES;" --connect-expired-password -u root -i -p''{{ mysql_temp_password.stdout }}'''
      when: mysql_temp_password.stdout != ''
      register: mysqlPasswordUpdated
      ignore_errors: yes

    - name: Start mysqld
      service:
        name: mysqld
        state: restarted

    - name: create wordpress db
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: create wordpress user
      mysql_user:
        name: wp_user
        password: "{{ wp_db_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: 'wordpress.*:ALL'
        state: present



    - name: Download wordpress tar
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Unarchive tar
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Copy wp_config file
      template:
        src:  templates/wp-config.php
        dest: /var/www/html/wp-config.php

    - name: Restart httpd
      service:
        name: httpd
        state: restarted