---
- name: Install wordpress
  hosts: dev
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Start and Enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Enable PHP 7.3
      shell: amazon-linux-extras disable php7.2 && amazon-linux-extras enable php7.3

    - name: Install PHP components
      shell: amazon-linux-extras install php7.3 -y

    - name: Install mysql repo
      yum:
        name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
        state: installed

    - name: Install mysql
      yum:
        name: mysql-community-server
        state: installed

    - name: Start mysqld
      service:
          name: mysql
          state: started
          enabled: yes

    - name: Download wordpress tar
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Unarchive tar
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Copy wp_config file
      template:
        src:  templates/wp-config.php
        dest: /var/www/html/wp-config.php

    - name: Restart httpd
      service:
        name: httpd
        state: restarted